### ISSUE TITLE
Format issues with the dataset

### ISSUE THREAD

**Issue by simingJin** [Precision-Vision/oed-classification-segmentation#1]
Hello author, may I ask what the approximate format of your dataset is? My current dataset format is as follows:
train:
-img
   1.png
   2.png
   ...
-mask
  1.png
  2.png
  ...
-json
  1.json
  2.json
  ...
What kind of data format is required for annotation

**Comment by abdol** [comment]
Hi @simingJin. The data loader was adapted to the format of the data annotation (i.e., XML annotations created by Aperio ImageScope). Currently, the loader reads data from the following file arrangement:

data [DATA ROOT]:
- mild [CLASS NAME]:
  - 10.123 [CASE NO]:
    - 1.jpg [IMAGE FILE]
    - 1.xml [XML ANNOTATION FILE]
  - 11.132
    -  1.jpg [IMAGE FILE]
    - 1.xml [XML ANNOTATION FILE]
   - ...
- moderate:
  - 12.333
  - 13.987
  - ... 
- severe:
  - ...

You can change how the data is processed by editing `LesionDataset` to your data requirements. Hope this helps.
